use_frameworks!
target 'GLMatrix_Tests' do
  pod 'GLMatrix', :path => '../'
  
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'swift-3.0'
  pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'swift-3.0'
end
